serveName: crontab
apiPort: 8070
apiReadTimeout: 5000
apiWriteTimeout: 5000
etcdEndpoints:
  -36.111.184.221:2379
etcdDialTimeout: 5000
mongodbUri: mongodb://36.111.184.221:27017
mongodbConnectTimeout: 5000